title: COURSE TITLE # title which appears for the website
email: #your-email@example.com
description: >- # short discription of your website
 
baseurl: orca_web_template   # specify the subpath of your site
url: https://atharva-chandak.github.io/ # the base hostname & protocol for YOUR site, e.g. http://example.com
twitter_username: #
github_username: #
theme: minima
plugins:
  - jekyll-feed
